### PR TITLE
added options to the module - sort, order

### PR DESCRIPTION
**Pull request by maddhruv**

### CODE REVIEW

**Comment by bnb** [comment]
If we are doing this in the module, we should probably also remove the `sort` from each of the queries in [data/projects.json](https://github.com/bnb/good-first-issue/blob/master/data/projects.json).

**Comment by maddhruv** [comment]
as` this.sort == query.sort`
we can remove the query.sort :+1:

**Comment by bnb** [comment]
If you could do that in this PR we can land it 👍

**Comment by maddhruv** [comment]
did it

**Comment by bnb** [comment]
A few notes on this:

- We're passing the options directly to Octokit, which is AWESOME! This means that `per_page` and `page` work by default.
  - We should also document that `per_page` and `page` work just fine  when passed 👍
- We're _also_ enabling users to pass `q`, which overwrites the Good First issue query defined by the passed project.
  - Instead of putting `q` into a black hole so it won't overwrite our queries, we should try to leverage this ability to dynamically add additional context to the base query

Here's an image of what happens when I pass `q: 'gcc'` to a custom example I built out to test this (I'll submit it as a PR separately):

image

We need to handle `q` before landing this 👍

**Comment by bnb** [comment]
Since we've got some open PRs that can currently land and were waiting on this one as 0.15.0, I've changed this to 0.16.0 and am going to ship another as 0.15.0 for now 👍

**Comment by bnb** [comment]
Going to remove the milestone for now until this is ready to land, at which point it will be whatever the next minor is.

**Comment by bnb** [comment]
@maddhruv is this still a goal? If so, can it be cleaned up? If not, can it be closed? 🙏

**Comment by maddhruv** [comment]
as of now
it is not
and has gone a little messy
closing

**Pull request closed without merging**
