### PR TITLE
organize projects in alphabetical order

### PR DESCRIPTION
**Pull request by tiaguinho**
I think this change help users to find the package more easily.

### CODE REVIEW

**Comment by hemal7735** [comment]
@tiaguinho yes, I was thinking about this for a very long time. It is a great idea to be honest.

1. `feeling-lucky` can be exempted from priority ? 😉 cc: @bnb for more info.
2. Instead of manually sorting the projects can we can do it programmatically. Adding a test would ensure that it is indeed sorted before every commit. We did something similar for markdown  [test: add markdown test for projects](https://github.com/bnb/good-first-issue/pull/79).

Do let me know if you need any more help!

**Comment by tiaguinho** [comment]
1. What is the ```feeling-lucky```?
2. Agree, doing this programmatically can help avoid mistakes.

**Comment by hemal7735** [comment]
`feeling-lucky` grabs an issue from random project. 😄

**Comment by bnb** [comment]
Resolved merge conflicts. Going to get CI fixed and once that passes we can merge.

**Comment by bnb** [comment]
Can't trigger a build so that's fun. Let's merge and see what breaks – can revert if necessary.

**Pull request merged**
