### PR TITLE
feat: Added npm start script

### PR DESCRIPTION
**Pull request by JacobRReed**
For developer ease of use

### CODE REVIEW

**Comment by JacobRReed** [comment]
closes #156

**Comment by bnb** [comment]
What is the benefit here / what does this solve?

**Comment by JacobRReed** [comment]
> What is the benefit here / what does this solve?

I guess it doesn't really solve anything :(, was just responding to a simple request some other dev made in #156

**Comment by bnb** [comment]
No worries, @JacobRReed! ❤️

Your PR is excellent – thanks for taking a stab at it! My only concern is that #156 is slightly mislead as an issue.

If you'd want to take a stab at another issue or pair on shipping a feature, I'd be more than happy to work on that with you, @JacobRReed 😀

**Comment by JacobRReed** [comment]
> n that with y

Ya, I haven't really got into contributing to open source before so I am just getting my feet wet really, trying to find stuff. Seems kind of hard, a lot of the projects I look at are either being tackled by 700 people already or are so complex they've been open for 2 years.
Most of my experience is in TS/JS and I have a lot of work in Angular and just starting in React. 
But ya, I'll take a look around here and there when I have time and see if there is anything I can help on :)

**Comment by bnb** [comment]
@JacobRReed I know exactly how you feel – was in a relatively similar position. More than happy to help get you started in various projects if that'd be helpful to you 👍

**Comment by bnb** [comment]
Going to close this for now. Again, happy to help move the needle for you @JacobRReed if you'd like some help :)

**Pull request closed without merging**
