### PR TITLE
added in Kleur

### PR DESCRIPTION
**Pull request by dhuang612**
removed Chalk from project and added in Kleur
ran npm tests and confirmed everything passed.
Please let me know if there is anything else I can change!

### CODE REVIEW

**Comment by bnb** [comment]
Other than personal preference, what is the benefit to this change?

**Comment by dhuang612** [comment]
The way this repo is using text markup is lightweight. Chalk provides a bunch of additional features that aren't used. You don't need to use a big bulky npm package like chalk to perform things that can be completed by Kleur.

It'll also help the program run quicker see these performance tests provided by Kleur
Screen Shot 2019-09-20 at 3 42 53 PM

https://www.npmjs.com/package/kleur/

**Comment by bnb** [comment]
So, the one challenge I have with this: we're not actually making good-first-issue lighter by moving to kleur – we're making it heavier. Both `boxen` and `inquirer` are already shipping with `chalk@2.4.2`. None of our dependencies are actually shipping `kleur`.

As such, by adding `kleur`, we're increasing our module size by 10kb rather than decreasing it by 80kb (which would be the case if `chalk` weren't required).

If you can convince one (or both!) of those modules to ship `kleur`, I'll merge this PR since at that point it'll be net neutral increase.

**Comment by dhuang612** [comment]
okay fair, let me see.

**Comment by bnb** [comment]
Since there's been no activity on this in a few months, going to close it.

**Pull request closed without merging**
